 name: TerraTool
 version: 0.2.0
 description: This plugin allows one terraform with a variety of tools
 # We could place every author in the authors list, but chose not to for illustrative purposes
 # Also, having an author distinguishes that person as the project lead, and ensures their
 # name is displayed first
 author: imattxc
 website: https://github.com/mmccoy37/GraffitiTools

 main: edu.gatech.mmccoy37.TerraTool.Main
 database: false
# depend: []

 commands:
   terratool:
     description: change tool settings
     aliases: [t,;]
     permission: terratool.use
     usage: |
       /t on\off
       /t size <number>
       /t tool <item name>
       /t brush <name>
       /t mod <modifier>
       /t place <block type>
       /t replace <old block type> OR <old block type> <new block type>
       /t undo <times>



